### ISSUE TITLE
Showing Other links of interests + people who saw this... Platform Details page

### ISSUE THREAD

**Issue by evaristoc** [evaristoc/fCC_R3#16]
## Problem Description
(...)

## User Story

- [x] Work on the corresponding services
- [x] Make a carousel of "Other links that might interest you..."
- [x] Make a carousel of "People who saw this were also interested on these..."
- [x] ~Reduce the number of rendered additional links to no more than 10, with an option to see more~ (considered another issue, #20)

##  Technical Specs

- [x] When selecting the platforms that go into the carousels, the data should be previously sorted according to relevance and then selecting the top 20 or less. 
- [ ] A correct implementation requires the technical specifications of this issue #11 to be solved

## Possible Solutions
* Options for "Other Similar Platforms of Interest":
1. ~Create a service to evaluate platforms of the same category and extract the top10~ **TECHNICAL CHALLENGES**: For firebase that would mean to call ALL PLATFORMS again and get into complex async queries, affecting performance as those have been already called for the main list
2. Create a list of top10 related platforms BEFORE loading to the database **TECHNICAL CHALLENGES**: this is the USUAL, MORE RECOMMENDED way to cope with data in firebase = flat and avoid queries; it has the additional advantage that complex relations can be found, like applying similarity formulas and attach  top10 similar ones to the selected platform; however, it is HARD to update: any new entry would imply that a lot, if not the whole, of the database should be revisited and updated. Depends of number of updates in terms of regularity and extension. It could be massive for a large dataset.

* Options for "People Who Saw This Also Saw That":
1. Possibly a very similar solution as above:  Create a list of top10 related platforms BEFORE loading to the database. See point 2 above for technical reasons and issues related to this proposal. Additionally implementing an query in firebase for this one is even more complex than for the previous one (detecting users -> going to users table to get all users and their suggestions -> go back to platform table to find all the suggestions). However, the table can be kept! I could be used for updates.

## Milestones
- [x] Make a simple implementation for this demo in order to evaluate LIF while still solving the corresponding issues
- [x] Work on database - see https://github.com/evaristoc/fCC_R3_DataAnalysis/milestones

---

### Warnings and Notes:
* An important note about **filtering with firebase in Angular**: https://angularfirebase.com/lessons/multi-property-data-filtering-with-firebase-and-angular-4/

### References:

For the Carousel:
* https://embed.plnkr.co/ScE0uqfd0ZvL6T9j1XjL/ (a more advanced one that should be modified to be simpler)
* https://scotch.io/tutorials/responsive-carousel-component-with-angular-2; https://embed.plnkr.co/VKLszgqJtobyVruBj3Op/ (a very simple one that should be modified to get more features)
* https://bootsnipp.com/snippets/featured/mega-menu-slide-down-on-hover-with-carousel
* https://www.w3schools.com/bootstrap/bootstrap_ref_js_carousel.asp
* https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-carousel.php
* https://getbootstrap.com/docs/3.3/examples/carousel/

For Sorting:
* https://stackoverflow.com/questions/39133217/how-can-i-sort-a-firebaselistobservable-list-in-angularfire2-angular2

**Comment by evaristoc** [comment]
For the Carousel:
* https://embed.plnkr.co/ScE0uqfd0ZvL6T9j1XjL/ (a more advanced one that should be modified to be simpler)
* https://scotch.io/tutorials/responsive-carousel-component-with-angular-2; https://embed.plnkr.co/VKLszgqJtobyVruBj3Op/ (a very simple one that should be modified to get more features)

**Comment by evaristoc** [comment]
This is being closed but this or similar will be have to be re-opened eventually after improving the ranking formula.

**Comment by evaristoc** [comment]
**Carousel** seems to be hard to implement for angular 2. The following solutions have been tried with undesired results or even no results:
1. https://scotch.io/tutorials/responsive-carousel-component-with-angular-2. Easy to implement if the number of elements is known in advance and it is fixed for all the occasions. Not the case, but it can be tweaked.
2. https://embed.plnkr.co/ScE0uqfd0ZvL6T9j1XjL/. Seems to be very appropriate for the case. Currently under study.
3. Using carouselamos (https://coursetro.com/posts/code/79/A-Quick-and-Easy-Angular-Carousel-in-a-Few-Minutes-(Angular-2-and-4+)). Didn't work, don't know why, it appears to be an issue with conflicting libraries?
4. ng-bootstrap carousel. Requires jQuery and other installations. Didn't go too long with it.

---

**Solution**:
From all the options available, ng-bootstrap has been the most straight forward and effective. Solution number 2 should be studied in depth as it gives more flexibility.
