### ISSUE TITLE
In the main list, present a description of the platforms based on relevant words instead

### ISSUE THREAD

**Issue by evaristoc** [evaristoc/fCC_R3#18]
## Problem Description
Because of project settings this data will be saved directly as a variable into the database for relevant words per subject instead of implementing a search, otherwise that would require a more complex implementation (eg. ElasticSearch database)

## User Story
- [ ] (...)

## Technical Specs
- [ ] I will use a specialized Service for this one.

## Possible Solutions
* This would required to add those lists in the database. Refers to this https://github.com/evaristoc/fCC_R3_DataAnalysis/issues/6. If not existing because not found, then I should select other clue.

## Milestones
- [ ] (...)

---

### Warnings and Notes:
* (...)

### References:
* http://beyondscheme.com/2016/angular2-discussion-portal
* https://stackoverflow.com/questions/43234724/angular2-retain-sensitive-information-after-browser-refresh

**Comment by evaristoc** [comment]
- [ ] This would required to add those lists in the database.

- [ ] If not existing because not found, then I should select other clue.

**Comment by evaristoc** [comment]
### Relevant Links:
* http://beyondscheme.com/2016/angular2-discussion-portal
* https://stackoverflow.com/questions/43234724/angular2-retain-sensitive-information-after-browser-refresh

I will use a specialized Service for this one.
